-- SPROC - LOAD GAME

CREATE PROCEDURE [DBO].[LOAD_GAME]
    @MLS_GAME_ID NVARCHAR(50) = NULL,
    @MIN_DATE DATETIME = NULL,
    @MAX_DATE DATETIME = NULL,
    @SEASON INT = NULL
AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON

	DROP TABLE IF EXISTS #GAME_IDS
    SELECT DISTINCT
        [GAME_ID] AS [MLS_GAME_ID]
	INTO #GAME_IDS
    FROM [MLS].[GAMES]
    WHERE (@MLS_GAME_ID IS NULL OR [GAME_ID] = @MLS_GAME_ID)
        AND (@MIN_DATE IS NULL OR [DATE_TIME_UTC] >= @MIN_DATE)
        AND (@MAX_DATE IS NULL OR [DATE_TIME_UTC] <= @MAX_DATE)
        AND (@SEASON IS NULL OR [SEASON_NAME] = @SEASON)

    BEGIN TRAN

		DELETE FROM [DBO].[GAME]
		WHERE [MLS_GAME_ID] IN (SELECT [MLS_GAME_ID] FROM #GAME_IDS)

		INSERT INTO [DBO].[GAME](
			[MLS_GAME_ID],
			[GAME_DATE],
			[SEASON],
			[HOME_TEAM],
			[AWAY_TEAM],
			[HOME_TEAM_MANAGER],
			[AWAY_TEAM_MANAGER],
			[REFEREE_NAME],
			[STADIUM_NAME],
			[ATTENDANCE],
			[MATCHDAY],
			[HOME_GOALS],
			[AWAY_GOALS],
			[GOAL_DIFFERENCE],
			[HOME_TEAM_EXPECTED_GOALS],
			[AWAY_TEAM_EXPECTED_GOALS],
			[HOME_PLAYER_EXPECTED_GOALS],
			[AWAY_PLAYER_EXPECTED_GOALS],
			[TEAM_EXPECTED_GOALS_DIFFERENCE],
			[PLAYER_EXPECTED_GOALS_DIFFERENCE],
			[FINAL_SCORE_DIFFERENCE],
			[EXPANDED_MINUTES],
			[IS_KNOCKOUT]
		)
		SELECT 
			G.[MLS_GAME_ID],
			MLS.[DATE_TIME_UTC] AS [GAME_DATE],
			MLS.[SEASON_NAME] AS [SEASON],
			MLS_H.[TEAM_ABBREVIATION] AS [HOME_TEAM],
			MLS_A.[TEAM_ABBREVIATION] AS [AWAY_TEAM],
			(
				SELECT MAX([MANAGER_NAME])
				FROM MLS.MANAGERS
				WHERE [MANAGER_ID] = MLS.[HOME_MANAGER_ID]
			) AS [HOME_TEAM_MANAGER],
			(
				SELECT MAX([MANAGER_NAME])
				FROM MLS.MANAGERS
				WHERE [MANAGER_ID] = MLS.[AWAY_MANAGER_ID]
			) AS [AWAY_TEAM_MANAGER],
			(
				SELECT MAX([REFEREE_NAME])
				FROM MLS.REFEREES
				WHERE [REFEREE_ID] = MLS.[REFEREE_ID]
			) AS [REFEREE_NAME],
			(
				SELECT MAX([STADIUM_NAME])
				FROM MLS.STADIUMS
				WHERE [STADIUM_ID] = MLS.[STADIUM_ID]
			),
			MLS.[ATTENDANCE],
			MLS.[MATCHDAY],
			MLS_XG.[HOME_GOALS] AS [HOME_GOALS],
			MLS_XG.[AWAY_GOALS] AS [AWAY_GOALS],
			MLS_XG.[GOAL_DIFFERENCE],
			MLS_XG.[HOME_TEAM_XGOALS] AS [HOME_TEAM_EXPECTED_GOALS],
			MLS_XG.[AWAY_TEAM_XGOALS] AS [AWAY_TEAM_EXPECTED_GOALS],
			MLS_XG.[HOME_PLAYER_XGOALS] AS [HOME_PLAYER_EXPECTED_GOALS],
			MLS_XG.[AWAY_PLAYER_XGOALS] AS [AWAY_PLAYER_EXPECTED_GOALS],
			MLS_XG.[TEAM_XGOAL_DIFFERENCE] AS [TEAM_EXPECTED_GOALS_DIFFERENCE],
			MLS_XG.[PLAYER_XGOAL_DIFFERENCE] AS [PLAYER_EXPECTED_GOALS_DIFFERENCE],
			MLS_XG.[FINAL_SCORE_DIFFERENCE],
			MLS.[EXPANDED_MINUTES],
			MLS.[KNOCKOUT_GAME] AS [IS_KNOCKOUT] 
		FROM #GAME_IDS AS G
		JOIN MLS.GAMES AS MLS ON G.[MLS_GAME_ID] = MLS.[GAME_ID]
		LEFT JOIN MLS.GAMES_XGOALS AS MLS_XG ON MLS.[GAME_ID] = MLS_XG.[GAME_ID]
		LEFT JOIN MLS.TEAMS AS MLS_H ON MLS.[HOME_TEAM_ID] = MLS_H.[TEAM_ID]
		LEFT JOIN MLS.TEAMS AS MLS_A ON MLS.[AWAY_TEAM_ID] = MLS_A.[TEAM_ID]

    COMMIT TRAN
            
END

-- SPROC - LOAD TEAM SALARIES
CREATE PROCEDURE [DBO].[LOAD_TEAM_SALARIES]
    @SEASON INT = 2024
AS
BEGIN
    -- SET NOCOUNT ON added to prevent extra result sets from
    -- interfering with SELECT statements.
    SET NOCOUNT ON

    BEGIN TRAN

        DELETE FROM [DBO].[TEAMS_SALARIES]
        WHERE [SEASON] = @SEASON

        INSERT INTO [DBO].[TEAM_SALARIES](
            [MLS_TEAM_ID],
            [SEASON],
            [TEAM],
            [COUNT_PLAYERS],
            [TOTAL_GUARANTEED_COMPENSATION],
            [AVG_GUARANTEED_COMPENSATION],
            [MEDIAN_GUARANTEED_COMPENSATION],
            [STD_DEV_GUARANTEED_COMPENSATION]
        )
        SELECT
            TS.[TEAM_ID] AS [MLS_TEAM_ID],
            TS.[SEASON_NAME] AS [SEASON],
            T.[TEAM_ABBREVIATION] AS [TEAM],
            TS.[COUNT_PLAYERS],
            TS.[TOTAL_GUARANTEED_COMPENSATION],
            TS.[AVG_GUARANTEED_COMPENSATION],
            TS.[MEDIAN_GUARANTEED_COMPENSATION],
            TS.[STD_DEV_GUARANTEED_COMPENSATION]
        FROM MLS.TEAMS_SALARIES TS
        LEFT JOIN MLS.TEAMS T ON TS.TEAM_ID = T.TEAM_ID
        WHERE TS.[SEASON_NAME] = @SEASON

    COMMIT TRAN
            
END
