CREATE TABLE [DBO].[GAME]
(
    [MLS_GAME_ID] NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS PRIMARY KEY,
    [GAME_DATE] DATE,
    [SEASON] INT,
    [HOME_TEAM] VARCHAR(5),
    [AWAY_TEAM] VARCHAR(5),
    [HOME_TEAM_MANAGER] VARCHAR(144),
    [AWAY_TEAM_MANAGER] VARCHAR(144),
    [REFEREE_NAME] VARCHAR(144),
    [STADIUM_NAME] VARCHAR(144),
    [ATTENDANCE] INT,
    [MATCHDAY] INT,
    [HOME_GOALS] INT,
    [AWAY_GOALS] INT,
    [GOAL_DIFFERENCE] INT,
    [HOME_TEAM_EXPECTED_GOALS] FLOAT,
    [AWAY_TEAM_EXPECTED_GOALS] FLOAT,
    [HOME_PLAYER_EXPECTED_GOALS] FLOAT,
    [AWAY_PLAYER_EXPECTED_GOALS] FLOAT,
    [TEAM_EXPECTED_GOALS_DIFFERENCE] FLOAT,
    [PLAYER_EXPECTED_GOALS_DIFFERENCE] FLOAT,
    [FINAL_SCORE_DIFFERENCE] INT,
    [EXPANDED_MINUTES] INT,
    [IS_KNOCKOUT] BIT,
    LAST_UPDATE DATETIME DEFAULT GETDATE(),
    CREATED_DATE DATETIME DEFAULT GETDATE()
);

CREATE TABLE [DBO].[TEAM_SALARIES](
    [MLS_TEAM_ID] [NVARCHAR](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TEAM] [VARCHAR](5) NULL, 
	[SEASON] [INT] NOT NULL,
	[COUNT_PLAYERS] [INT] NOT NULL,
	[TOTAL_GUARANTEED_COMPENSATION] [FLOAT] NOT NULL,
	[AVG_GUARANTEED_COMPENSATION] [FLOAT] NOT NULL,
	[MEDIAN_GUARANTEED_COMPENSATION] [FLOAT] NOT NULL,
	[STD_DEV_GUARANTEED_COMPENSATION] [FLOAT] NOT NULL,
	[CREATED_AT] [DATETIME] DEFAULT GETDATE() NOT NULL,
	PRIMARY KEY ([MLS_TEAM_ID], [SEASON_NAME])
);
